---
title: "CSOmap runDemo"
author: "Jason Li"
date: "`r Sys.Date()`"
output:
  html_notebook:
    fig_caption: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
---

```{r, echo=FALSE}
# !diagnostics off
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE
)
```

# Dependencies
```{r message=FALSE, warning=FALSE}
# dependencies
library("Seurat")
library("tidyverse")
library("assertthat")
library("reshape2")
library("tictoc")
require(umap)
require(Rtsne)

source("utils/utils.R")

```

# Run CSOmap in R

## Load dataset
```{r}
loginfo("Loading input file ...")
tic()
TPM_tbl <- read_tsv("/home/jason/git/CSOmapR/data/demo/TPM.txt")
LR <- read.table("/home/jason/git/CSOmapR/data/demo/LR_pairs.txt", header = FALSE, sep = "\t")
labelData <- read_tsv("/home/jason/git/CSOmapR/data/demo/label.txt")
toc()

# set variables & validation ----
TPM = as.matrix(TPM_tbl[,-1])
rownames(TPM) = TPM_tbl[, 1, drop = T] 
TPM[is.na(TPM)] = 0

```

# Run 5 times using origin / cpp-modified method
```{r}
out_dir = "/home/jason/git/CSOmapR/results/R/"
seeds = c(1:5)
time_tbl = tibble()
demoR_lst = list()
for(seed2set in seeds){
  affinityMat = getAffinityMat(TPM, LR)
  set.seed(seed2set)
  
  # Run cpp protocol ----
  tic(msg = paste0("cpp_0", seed2set, "_forCoord"))
  # get coordinates 
  coords <- optimization(affinityMat)
  time_used = toc()
  
  rownames(coords) <- colnames(TPM)
  colnames(coords) <- c('x', 'y', 'z')
  coords_tbl = bind_cols(cellName = rownames(coords), as.data.frame(coords))
  
  # Calling significance 
  tic(msg = "Calling significance")
  labels <- labelData[, 2, drop = T][match(colnames(TPM), labelData[,1,drop = T])]
  labels[is.na(labels)] = "unlabeled"
  # Get significance & get Connections
  signif_res = getSignificance(coords, labels = labels)
  toc()
  
  # store 
  join_vec = setNames(colnames(labelData)[1], nm = colnames(coords_tbl)[1])
  cellinfo_tbl = left_join(coords_tbl, labelData, by = join_vec)
  
  demoR_lst[[paste0("demo_0", seed2set, "_cpp")]] = list(coords = coords_tbl, signif_res = signif_res, cellinfo = cellinfo_tbl)
  
  time_tbl = bind_rows(time_tbl,
                       bind_rows(
                         tibble(
                           item = "cpp",
                           seed = seed2set,
                           time_elapsed = time_used$toc - time_used$tic
                         )
                       ))
  
  # Run origin protocol ----
  tic(msg = paste0("origin_0", seed2set, "_forCoord"))
  # get coordinates 
  # coords = getCoordinates(TPM, LR, version = "origin")
  coords <- optimization_origin(affinityMat)
  time_used = toc()
  
  rownames(coords) <- colnames(TPM)
  colnames(coords) <- c('x', 'y', 'z')
  coords_tbl = bind_cols(cellName = rownames(coords), as.data.frame(coords))
  
  # Calling significance 
  tic(msg = "Calling significance")
  labels <- labelData[, 2, drop = T][match(colnames(TPM), labelData[,1,drop = T])]
  labels[is.na(labels)] = "unlabeled"
  # Get significance & get Connections
  signif_res = getSignificance(coords, labels = labels)
  toc()
  
  # store cell info
  join_vec = setNames(colnames(labelData)[1], nm = colnames(coords_tbl)[1])
  cellinfo_tbl = left_join(coords_tbl, labelData, by = join_vec)
  
  # store
  demoR_lst[[paste0("demo_0", seed2set, "_origin")]] = list(coords = coords_tbl, signif_res = signif_res, cellinfo = cellinfo_tbl)
  
  time_tbl = bind_rows(time_tbl,
                       bind_rows(
                         tibble(
                           item = "origin.R",
                           seed = seed2set,
                           time_elapsed = time_used$toc - time_used$tic
                         )
                       ))
  
  # Use Rtsne as optimization method ----
  for(theta2use in seq(0, 0.8, by = 0.2)) {
    tic(msg = paste0("Rtsne_", theta2use, "_0", seed2set, "_forCoord"))
    # get coordinates
    # coords = getCoordinates(TPM, LR, version = "origin")
    coords_res <-
      Rtsne::Rtsne(affinityMat,
                   dims = 3,
                   theta = theta2use,
                   max_iter = 1000)
    time_used = toc()
    coords = coords_res$Y
    rownames(coords) <- colnames(TPM)
    colnames(coords) <- c('x', 'y', 'z')
    coords_tbl = bind_cols(cellName = rownames(coords), as.data.frame(coords))
    
    # Calling significance
    tic(msg = "Calling significance")
    labels <-
      labelData[, 2, drop = T][match(colnames(TPM), labelData[, 1, drop = T])]
    labels[is.na(labels)] = "unlabeled"
    # Get significance & get Connections
    signif_res = getSignificance(coords, labels = labels)
    toc()
    
    # store cell info
    join_vec = setNames(colnames(labelData)[1], nm = colnames(coords_tbl)[1])
    cellinfo_tbl = left_join(coords_tbl, labelData, by = join_vec)
    
    # store
    demoR_lst[[paste0("demo_0", seed2set, "_Rtsne_", theta2use)]] = 
      list(coords = coords_tbl,
           signif_res = signif_res,
           cellinfo = cellinfo_tbl)
    
    time_tbl = bind_rows(time_tbl,
                         bind_rows(
                           tibble(
                             item = paste0("Rtsne", "_", theta2use),
                             seed = seed2set,
                             time_elapsed = time_used$toc - time_used$tic
                           )
                         ))
    
  }
  
  # Use umap as optimization method, range unnormalized ----
  dist_mt = max(affinityMat) - affinityMat
  umap.defaults$n_components = 3
  umap.defaults$input = "dist"
  tic(msg = paste0("umap_0", seed2set, "_maxSubset"))
  # get coordinates 
  coords_res <- umap::umap(dist_mt, config = umap.defaults, method = "umap-learn")
  time_used = toc()
  
  coords = coords_res$layout
  rownames(coords) <- colnames(TPM)
  colnames(coords) <- c('x', 'y', 'z')
  coords_tbl = bind_cols(cellName = rownames(coords), as.data.frame(coords))
  
  # Calling significance 
  tic(msg = "Calling significance")
  labels <- labelData[, 2, drop = T][match(colnames(TPM), labelData[,1,drop = T])]
  labels[is.na(labels)] = "unlabeled"
  # Get significance & get Connections
  signif_res = getSignificance(coords, labels = labels)
  toc()
  
  # store cell info
  join_vec = setNames(colnames(labelData)[1], nm = colnames(coords_tbl)[1])
  cellinfo_tbl = left_join(coords_tbl, labelData, by = join_vec)
  
  # store
  demoR_lst[[paste0("demo_0", seed2set, "_umap_direct")]] = list(coords = coords_tbl, signif_res = signif_res, cellinfo = cellinfo_tbl)
  
  time_tbl = bind_rows(time_tbl,
                       bind_rows(
                         tibble(
                           item = "umap_direct",
                           seed = seed2set,
                           time_elapsed = time_used$toc - time_used$tic
                         )
                       ))
  
  # Use umap as optimization method, affinity 2 dist, range normalized ----
  dist_mt = (max(affinityMat) - affinityMat)/(max(affinityMat) - min(affinityMat))
  umap.defaults$n_components = 3
  umap.defaults$input = "dist"
  tic(msg = paste0("umap_0", seed2set, "_maxNorm"))
  # get coordinates 
  coords_res <- umap::umap(dist_mt, config = umap.defaults, method = "umap-learn")
  time_used = toc()
  
  coords = coords_res$layout
  rownames(coords) <- colnames(TPM)
  colnames(coords) <- c('x', 'y', 'z')
  coords_tbl = bind_cols(cellName = rownames(coords), as.data.frame(coords))
  
  # Calling significance 
  tic(msg = "Calling significance")
  labels <- labelData[, 2, drop = T][match(colnames(TPM), labelData[,1,drop = T])]
  labels[is.na(labels)] = "unlabeled"
  # Get significance & get Connections
  signif_res = getSignificance(coords, labels = labels)
  toc()
  
  # store cell info
  join_vec = setNames(colnames(labelData)[1], nm = colnames(coords_tbl)[1])
  cellinfo_tbl = left_join(coords_tbl, labelData, by = join_vec)
  
  # store
  demoR_lst[[paste0("demo_0", seed2set, "_umap_normalizedDist")]] = list(coords = coords_tbl, signif_res = signif_res, cellinfo = cellinfo_tbl)
  
  time_tbl = bind_rows(time_tbl,
                       bind_rows(
                         tibble(
                           item = "umap_normalizedDist",
                           seed = seed2set,
                           time_elapsed = time_used$toc - time_used$tic
                         )
                       ))
}

write_rds(demoR_lst, path = paste0(out_dir, "demoR_lst.Rds"))
write_csv(time_tbl, path = paste0(out_dir, "time_tbl.csv"))
```


