---
title: "CSOmap benchmarking"
author: "Jason Li"
date: "`r Sys.Date()`"
output:
  html_notebook:
    fig_caption: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
---

```{r, echo=FALSE}
# !diagnostics off
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE
)
```

# Dependencies
```{r message=FALSE, warning=FALSE}
# dependencies
library("Seurat")
library("tidyverse")
library("assertthat")
library("reshape2")
library("tictoc")

source("utils/utils.R")

```

# Load results
## R
```{r, fig.width=7, fig.height=6}
data_dir = "/home/jason/git/CSOmapR/results/R/"
demoR_lst = read_rds(paste0(data_dir, "demoR_lst.Rds"))
time_tbl = read_csv(paste0(data_dir, "time_tbl.csv"))

time_all_tbl = bind_rows(
  time_tbl, 
  tibble(
    item = "matlab",
    seed = 1:5,
    time_elapsed = c(
      13.081, 13.656, 13.509, 13.413, 13.238
    )
  )
)

time_all_tbl$item[time_all_tbl$item == "matlab"] = "origin.matlab"
# time_all_tbl$item[time_all_tbl$item == "origin"] = "origin.R"
time_all_tbl$item[time_all_tbl$item == "cpp"] = "Rcpp"
time_all_tbl$item = factor(time_all_tbl$item, levels = c("origin.matlab", "origin.R", "Rcpp", "Rtsne_0", "Rtsne_0.2", "Rtsne_0.4", "Rtsne_0.6", "Rtsne_0.8", "umap_direct", "umap_normalizedDist"))

time_all_tbl %>% 
  group_by(item) %>% summarise(mean = mean(time_elapsed), sd = sd(time_elapsed)) %>% 
  ggplot(aes(x = item, y = mean)) +
  geom_col(width = 0.6, fill = "white", color = "black") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean+sd), width = 0.4 )+
  geom_text(aes(label = round(mean, 2)), vjust = -1) +
  theme_classic(base_size = 20) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.1))) +
  labs(y = "Mean of time cost (seconds)", x = "Pipeline (n=5)", title = "Comparison of time cost of optimization") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
  
```

## matlab
```{r}
demoMatlab_lst = list()
data_dir = "/home/jason/git/CSOmapR/results/matlab/"
demoMatlab_dirs = Sys.glob(paste0(data_dir, "demo*"))
for(dir2read in demoMatlab_dirs){
  sample_name = str_extract(dir2read, pattern = "demo_\\d+")
  coords_tbl = read_tsv(paste0(dir2read, "/result/", sample_name, "_coordinate.txt"))
  
  connections_tbl = read_tsv(paste0(dir2read, "/result/", sample_name, "_connections.txt"))
  connections_mt = connections_tbl[, -c(1, ncol(connections_tbl))] %>% as.matrix()
  rownames(connections_mt) = connections_tbl$number
  
  pvalue_raw_tbl = read_tsv(paste0(dir2read, "/result/", sample_name, "_statistics.txt"))
  pvalue_mt = pvalue_raw_tbl[, -c(1, ncol(pvalue_raw_tbl))] %>% as.matrix()
  rownames(pvalue_mt) = pvalue_raw_tbl$`p-value`
  pvalue_tbl = pvalue_mt  %>% melt(varnames = c("cluster1", "cluster2"), value.name = "q.value") %>% 
    unite(col = "cluster_pair", cluster1, cluster2, sep = "---", remove = T)
  
  label_tbl = read_tsv(paste0(dir2read, "/label.txt"))
  
  cellinfo_tbl = left_join(coords_tbl, label_tbl, by = c("ID" = "cells"))
  cellinfo_tbl$labels[is.na(cellinfo_tbl$labels)] = "unlabeled"
  
  
  coords = cellinfo_tbl[, c("x", "y", "z")] %>% as.matrix()
  rownames(coords) = cellinfo_tbl$ID
  labels = cellinfo_tbl$labels
  signif_res = getSignificance(coords, labels = labels)
  
  demoMatlab_lst[[paste0(sample_name, "_matlab")]] = list(
    coords = coords_tbl, 
    signif_res = signif_res,
    # signif_res = list(
    #   connections = connections_mt, 
    #   pvalue_tbl = pvalue_tbl
    # ), 
    cellinfo = cellinfo_tbl
  )
}

demoAll_lst = c(demoR_lst, demoMatlab_lst)
```

# Check density plot
```{r}
plt_dir = "/home/jason/git/CSOmapR/results/3Dplots/"
color_labels = setNames(
  c("#FF2929", "#FF4ADB", "#B725FA", "#672BFF", "#3ADAFA", "#38FFA2", "#FFE138", "#FF9029", "#C7C7C7"),
  nm = unique(label_tbl$labels) %>% sort())
for(chosen_sample in names(demoAll_lst)){
  plt_tbl = demoAll_lst[[chosen_sample]]$cellinfo
  plt_tbl$labels[is.na(plt_tbl$labels)] = "unlabeled"
  
  density_obj = getDensity3D(plt_tbl$x, plt_tbl$y, plt_tbl$z)
  plt_tbl = plt_tbl %>% mutate(density = density_obj)
  
  require(plotly)
  fig_density = plot_ly(
    plt_tbl,
    x = ~ x,
    y = ~ y,
    z = ~ z,
    alpha = 0.4,
    color = ~ density
  )  %>% add_markers() %>%
    layout(title = paste0("3D density of ", chosen_sample))
  
  htmlwidgets::saveWidget(
    fig_density,
    file = paste0(plt_dir, chosen_sample, "_density.html"),
    selfcontained = F,
    libdir = paste0(plt_dir, "lib/")
  )
  
  fig_label = plot_ly(
    plt_tbl,
    x = ~ x,
    y = ~ y,
    z = ~ z,
    alpha = 0.4,
    color = ~ labels,
    colors = color_labels
  )  %>% add_markers() %>%
    layout(title = paste0("Labels of ", chosen_sample))
  #print(fig_label)
  
  htmlwidgets::saveWidget(
    fig_density,
    file = paste0(plt_dir, chosen_sample, "_labels.html"),
    selfcontained = F,
    libdir = paste0(plt_dir, "lib/")
  )
}

```

# Connection comparison
```{r, fig.height=12, fig.width=12}
all_connection_tbl = tibble()
for(chosen_sample in names(demoAll_lst)){
  connection_mt = demoAll_lst[[chosen_sample]]$signif_res$connections
  connection_tbl = connection_mt %>% 
    melt(varnames = c("cluster1", "cluster2"), value.name = "connections") %>% 
    mutate(sample_name = chosen_sample) %>% 
    unite(col = "cluster_pair", cluster1, cluster2, sep = "---", remove = T)
  all_connection_tbl = bind_rows(
    all_connection_tbl, 
    connection_tbl
  )
}
test_mt = all_connection_tbl %>% acast(cluster_pair ~ sample_name, value.var = "connections", fill = 0)
# cor_mt =  cor(test_mt, method = "spearman")
colnames(test_mt) = colnames(test_mt) %>% str_replace(pattern = "_origin", replacement = "_origin.R")
colnames(test_mt) = colnames(test_mt) %>% str_replace(pattern = "_matlab", replacement = "_origin.matlab")
colnames(test_mt) = colnames(test_mt) %>% str_replace(pattern = "_cpp", replacement = "_Rcpp")

require(ComplexHeatmap)
col_fun = circlize::colorRamp2(c(0, 1), c("white", "red"))
cor_mt =  cor(test_mt, method = "pearson")
ComplexHeatmap::Heatmap(cor_mt, name = "Pearson correlation", col = col_fun)
cor_mt =  cor(test_mt, method = "spearman")
ComplexHeatmap::Heatmap(cor_mt, name = "Spearman correlation", col = col_fun)

```

```{r, fig.width=16, fig.height=11}
# Connection 
ComplexHeatmap::Heatmap(t(test_mt), name = "Connection")
```
# Consistency of significance
```{r, fig.height=10, fig.width=14}
signif_tbl = tibble()
for(chosen_sample in names(demoAll_lst)){
  signif_tbl = 
    bind_rows(
      signif_tbl, 
      demoAll_lst[[chosen_sample]]$signif_res$pvalue_tbl %>% 
        dplyr::select(cluster_pair, q.value) %>% 
        dplyr::mutate(sample_name = chosen_sample)
    )
}

# plot a heatmap
plt_mt = signif_tbl %>% acast(cluster_pair ~ sample_name, value.var = "q.value", fill = 1)
plt_mt = -log10(plt_mt + 1e-3)

col_fun = circlize::colorRamp2(c(0, 1.3, 3), c("blue", "white", "red"))
ComplexHeatmap::Heatmap(t(plt_mt), name = "-log10(q.value)", col = col_fun)
```


