// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_d_rcpp
MatrixXd calc_d_rcpp(MatrixXd ydata);
RcppExport SEXP _CSOmapR_calc_d_rcpp(SEXP ydataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MatrixXd >::type ydata(ydataSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_d_rcpp(ydata));
    return rcpp_result_gen;
END_RCPP
}
// update_grads_rcpp
MatrixXd update_grads_rcpp(MatrixXd grads, MatrixXd ydata, MatrixXd stiffnesses);
RcppExport SEXP _CSOmapR_update_grads_rcpp(SEXP gradsSEXP, SEXP ydataSEXP, SEXP stiffnessesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MatrixXd >::type grads(gradsSEXP);
    Rcpp::traits::input_parameter< MatrixXd >::type ydata(ydataSEXP);
    Rcpp::traits::input_parameter< MatrixXd >::type stiffnesses(stiffnessesSEXP);
    rcpp_result_gen = Rcpp::wrap(update_grads_rcpp(grads, ydata, stiffnesses));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CSOmapR_calc_d_rcpp", (DL_FUNC) &_CSOmapR_calc_d_rcpp, 1},
    {"_CSOmapR_update_grads_rcpp", (DL_FUNC) &_CSOmapR_update_grads_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CSOmapR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
