# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_d_rcpp <- function(ydata) {
    .Call(`_CSOmapR_calc_d_rcpp`, ydata)
}

update_grads_rcpp <- function(grads, ydata, stiffnesses) {
    .Call(`_CSOmapR_update_grads_rcpp`, grads, ydata, stiffnesses)
}

