# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runExactTSNE_wrapper <- function(X, no_dims, verbose, max_iter, Y_in, init, rand_seed, skip_random_init, max_step_norm, mom_switch_iter, momentum, final_momentum, df) {
    .Call(`_CSOmapR_runExactTSNE_wrapper`, X, no_dims, verbose, max_iter, Y_in, init, rand_seed, skip_random_init, max_step_norm, mom_switch_iter, momentum, final_momentum, df)
}

#' Calculate d using Rcpp
#' 
#' @param ydata a matrix of coordinates
#' @return d
#' 
calc_d_rcpp <- function(ydata) {
    .Call(`_CSOmapR_calc_d_rcpp`, ydata)
}

#' Update gradients using Rcpp
#' 
#' @param grads a matrix of gradients
#' @param ydata a matrix of coordinates
#' @param stiffnesses a matrix of stiffnesses
#' @return updated grads
#' 
update_grads_rcpp <- function(grads, ydata, stiffnesses) {
    .Call(`_CSOmapR_update_grads_rcpp`, grads, ydata, stiffnesses)
}

