# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rtsne_cpp <- function(X, no_dims, perplexity, theta, verbose, max_iter, distance_precomputed, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, eta, exaggeration_factor, num_threads) {
    .Call(`_CSOmapR_Rtsne_cpp`, X, no_dims, perplexity, theta, verbose, max_iter, distance_precomputed, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, eta, exaggeration_factor, num_threads)
}

Rtsne_nn_cpp <- function(nn_dex, nn_dist, no_dims, perplexity, theta, verbose, max_iter, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, eta, exaggeration_factor, num_threads) {
    .Call(`_CSOmapR_Rtsne_nn_cpp`, nn_dex, nn_dist, no_dims, perplexity, theta, verbose, max_iter, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, eta, exaggeration_factor, num_threads)
}

#' Calculate d using Rcpp
#' 
#' @param ydata a matrix of coordinates
#' @return d
#' 
calc_d_rcpp <- function(ydata) {
    .Call(`_CSOmapR_calc_d_rcpp`, ydata)
}

#' Update gradients using Rcpp
#' 
#' @param grads a matrix of gradients
#' @param ydata a matrix of coordinates
#' @param stiffnesses a matrix of stiffnesses
#' @return updated grads
#' 
update_grads_rcpp <- function(grads, ydata, stiffnesses) {
    .Call(`_CSOmapR_update_grads_rcpp`, grads, ydata, stiffnesses)
}

normalize_input_cpp <- function(input) {
    .Call(`_CSOmapR_normalize_input_cpp`, input)
}

